name: Purge jsDelivr Cache on Push

on:
  push:
    branches:
      - main  # غيّرها لو اسم الـ branch مختلف (master مثلاً)

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - name: Purge version.txt
        uses: egad13/purge-jsdelivr-cache@v1
        with:
          urls: |
            https://cdn.jsdelivr.net/gh/xerostore43-eng/xero-data@main/version.txt
            https://cdn.jsdelivr.net/gh/xerostore43-eng/xero-data@main/xerobase.exe
            https://cdn.jsdelivr.net/gh/xerostore43-eng/xero-data@main/data.json
