name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main          # غيّرها لـ master لو branch اسمها كده

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        uses: egad13/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/xerostore43-eng/xero-data@main/version.txt
            https://cdn.jsdelivr.net/gh/xerostore43-eng/xero-data@main/xerobase.exe
            https://cdn.jsdelivr.net/gh/xerostore43-eng/xero-data@main/data.json
            # أضف أي ملفات تانية هنا، كل واحد في سطر
